#!/bin/sh
# Guest-side probe for testing isolation inside the VM.
# This script runs inside the guest VM and checks what resources are visible/blocked.

echo "{"
echo "  \"environment\": {"
echo "    \"user\": \"$(whoami 2>/dev/null || echo unknown)\","
echo "    \"home\": \"$HOME\","
echo "    \"cwd\": \"$(pwd)\","
echo "    \"firejail_binary_present\": $([ -x /usr/local/bin/firejail ] && echo true || echo false),"
echo "    \"firejail_runs\": $(/usr/local/bin/firejail --version >/dev/null 2>&1 && echo true || echo false)"
echo "  },"
echo "  \"sensitive_paths\": {"
echo "    \"home_ssh\": $([ -d "$HOME/.ssh" ] && echo true || echo false),"
echo "    \"home_aws\": $([ -d "$HOME/.aws" ] && echo true || echo false),"
echo "    \"home_gnupg\": $([ -d "$HOME/.gnupg" ] && echo true || echo false),"
echo "    \"etc_shadow\": $([ -r /etc/shadow ] && echo true || echo false),"
echo "    \"proc_kcore\": $([ -r /proc/kcore ] && echo true || echo false)"
echo "  },"
echo "  \"devices\": {"
echo "    \"dev_kvm\": $([ -e /dev/kvm ] && echo true || echo false),"
echo "    \"dev_sda\": $([ -e /dev/sda ] && echo true || echo false),"
echo "    \"dev_vda\": $([ -e /dev/vda ] && echo true || echo false)"
echo "  },"
echo "  \"network\": {"
echo "    \"proc_net_tcp\": $([ -r /proc/net/tcp ] && echo true || echo false),"
echo "    \"etc_resolv_conf\": $([ -r /etc/resolv.conf ] && echo true || echo false)"
echo "  }"
echo "}"
